INSERT INTO USER_RIGHTS_LIB (ID, SHORTD, LONGD) VALUES (1,'EU','End User');
INSERT INTO USER_RIGHTS_LIB (ID, SHORTD, LONGD) VALUES (2,'GSU','General Services Unit');
INSERT INTO USER_RIGHTS_LIB (ID, SHORTD, LONGD) VALUES (3,'FMS','Fund Management Section');
INSERT INTO USER_RIGHTS_LIB (ID, SHORTD, LONGD) VALUES (4,'ORVP','Office of the Regional Vice President');
INSERT INTO USER_RIGHTS_LIB (ID, SHORTD, LONGD) VALUES (5,'C','Cashier');



INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '1', '2', 'EU', 'Create RIV & Get Clearance from Division Head');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '2', '3', 'GSU', 'GSU - Check APP and Assign Series Number');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV ', '3', '4', 'FMS', 'Check Budget and Clear');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '4', '5', 'ORVP', 'Approve RIV');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '5', '6', 'GSU', 'Prepare CQ, CA, and PO');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '6', '7', 'FMS', 'Approve AC and PO');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '7', '8', 'ORVP', 'Approve PO');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '8', '9', 'GSU', 'Prepare DV');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '9', '10', 'Cashier', 'Issue Check(s)');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '10', '11', 'GSU', 'Serve Payment and Acquire Items');
INSERT INTO FLOW_LIB (FTYPE, FLOW_ID, NEXT_ID, RIGHTS, DESCRIPTION) VALUES ('RIV', '11', '0', 'EU', 'Receive Supplies via Withdrawal Slip');


